config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :books do
    resources :shares, only: [:index, :create, :update]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  get 'our_mission', to: 'pages#our_mission'
  get 'self_publication', to: 'pages#self_publication'
  get 'learn_investment', to: 'pages#learn_investment'

  resources :shares, only: [:index, :delete]
  get '/tagged', to: "books#tagged", as: :tagged
  get 'user_balance', to: 'pages#user_balance'
  post 'user_balance', to: 'pages#add_user_balance'

  get 'wallets', to: 'pages#wallets'
  # get 'payments', to: 'pages#payements'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :shares, dependent: :destroy
  validates :title, :description, :initial_share_value, :total_amount, presence: true
  has_one_attached :photo

  acts_as_taggable_on :tags

  # def share_value
  #   :value / :total_amount
  # end
end

app/models/cash_wallet.rb
class CashWallet < ApplicationRecord
  # monetize :price_cents
end

app/models/investor.rb
class Investor < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cash_wallet
  # monetize :amount_cents

  def show
    @order = current_user.orders.find(params[:id])
  end
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :shares, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_tags, only: [:index, :new, :update]

  def index
    @books = Book.all
    @selected_cats = []
    if params.keys.size > 3
      @selected_cats = params.keys
      filtered_books = []
      @books.each do |book|
        book.tag_list.each do |tag|
          if @selected_cats.include?(tag)
            filtered_books << book unless filtered_books.include?(book)
          end
        end
      end
      @books = filtered_books
    end
  end

  def show
    @book = Book.find(params[:id])
    @section = params[:section] || 'description'
    @related_books = @book.find_related_tags
    @share = Share.new
    @my_shares = Share.where(user_id: current_user.id, book_id: @book.id)
    @share_amount = @my_shares ? @my_shares.map { |share| share.share_amount }.sum() || 0 : 0
    total_shares_distr = Share.where(book_id: @book.id).map { |share| share.share_amount }.sum() || 0
    @total_shares_remain = @book.total_amount - total_shares_distr
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.current_share_value = @book.initial_share_value
    @book.user = current_user
    if @book.save
      redirect_to book_path(@book), notice: "Congratulations! Your book is now on the market", class: "btn btn-outline-secondary"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
    @book.user = current_user
  end

  def update
    @book = Book.find(params[:id])
    @book.current_share_value = @book.initial_share_value
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def tagged
    if params[:tag].present?
      @books = Book.tagged_with(params[:tag])
    else
      @books = Book.all
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :psuedoname, :author_description, :description, :initial_share_value, :total_amount, :photo, :example, tag_list: [])
  end

  def set_tags
    @tags = ["Fantasy", "Romance", "Mystery", "Horror", "Thriller", "Paranormal", "Historical Fiction", "Sci-Fi", "Dystopian", "Memoir", "Art", "Self Help", "Motivational", "Health", "History", "Travel Guide", "Cookbook", "Poetry", "Erotic", "Female Author", "Trans Author", "Queer Author", "Non-Binary Author", "POC Author", "Black Author", "Asian Author", "LatinX Author", "Indegenous Author", "Agender Author", "Polysexual Author", "Disabled Author", "Neurodivergent Author", "Literary Prize", "Critically Acclaimed", "Dark", "Cerebral", "Inspiring", "Slow-Burn", "Psychological", "Quirky", "Coming Of Age", "Cultural", "Social Commentary", "Sunday Reading", "Guilty Pleasure", "Strong Female Lead", "Queer Romance" ]
  end
end

app/controllers/investor_controller.rb
class InvestorController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = current_user.orders.find(params[:id])
  end

  def create
    cash_wallet = CashWallet.find(params[:cash_wallet_id])
    order = Order.create!(cash_wallet: cash_wallet, amount_cents: cash_wallet.price_cents, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        quantity: 1,
        price_data: {
          unit_amount: cash_wallet.price_cents,
          currency: 'eur',
          product_data: {
            name: cash_wallet.cash_value
          }
        }
      }],
      mode: "payment",
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)

    current_user.update(balance: current_user.balance + (cash_wallet.price_cents / 100))
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def user_balance
  end

  def add_user_balance
    balance = params[:balance].to_f
    current_user.balance += balance
    if current_user.save
      redirect_to shares_path
    else
      render "user_balance", status: :unprocessable_entity
    end
  end


  def wallets
    @wallets = CashWallet.all
  end

  def our_mission
  end

  def self_publication
  end

  def learn_investment
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def index
    @shares = current_user.shares
  end

  def create
    @book = Book.find(params[:book_id])
    @share = Share.new(share_params)
    @share.share_value = @book.current_share_value
    @share.user = current_user
    @share.book = @book
    if params[:buy]
      current_user.update(balance: current_user.balance - params["selected-value"].to_f)
      @book.current_share_value = (1 + @share.share_amount/100) * (@book.current_share_value * rand(1.01...1.05))
    elsif params[:sell]
      current_user.update(balance: current_user.balance + params["selected-value"].to_f)
      @book.current_share_value = (1 + @share.share_amount/100) * (@book.current_share_value * rand(0.95...0.99))
      @share.share_amount = -@share.share_amount
    end
    @book.save
    if @share.save
      redirect_to book_path(@book), notice: "Added To Portfolio!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def share_params
    params.require(:share).permit(:share_amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<div class="container">
  <h1>Update your book: <%= @book.title %></h1>

  <%= render "shared/simple_form", book: @book %>

</div>

app/views/books/index.html.erb
<div class="container">
  <div class="all-books">
    <div class="title">
      <h1 class="title-books">All<br>books</h1>
    </div>
    <div class="dashboard">
      <%= render "shared/dashboard", width: "width: 800px;" %>
    </div>
  </div>

    <% cats = [ "Fantasy", "Romance", "Mystery", "Horror", "Thriller", "Paranormal", "Historical Fiction", "Sci-Fi", "Dystopian", "Memoir", "Art", "Self Help", "Motivational", "Health", "History", "Travel Guide", "Cookbook", "Poetry", "Erotic", "Female Author", "Trans Author", "Queer Author", "Non-Binary Author", "POC Author", "Black Author", "Asian Author", "LatinX Author", "Indegenous Author", "Agender Author", "Polysexual Author", "Disabled Author", "Neurodivergent Author", "Literary Prize", "Critically Acclaimed", "Dark", "Cerebral", "Inspiring", "Slow-Burn", "Psychological", "Quirky", "Coming Of Age", "Cultural", "Social Commentary", "Sunday Reading", "Guilty Pleasure", "Strong Female Lead", "Queer Romance", "Manga/Anime", "Graphic Novel", "Children's Book", "Design"] %>

    <%= form_with url: books_path, method: :get, html: {class: "my-4", data: {search_books_target: "form", controller: "tag-list"}} do |f| %>
      <div id="checkboxes">
        <% cats.each do |item| %>
            <label for="<%= item %>" class="checkbox-tag" data-tag-list-target="checkbox" data-action="click->tag-list#toggleActive">
            <input name="<%= item %>[<%= item %>]" class="checkbox checkbox-tag-input" type="checkbox" id="<%= item %>"  value="<%= @selected_cats.include?(item)? "1" : "0"%>"><%= item %></label>
        <% end %>
        <%= f.submit class: "btn btn-outline-dark" %>
      </div>
    <% end %>
  <p>
    <% if @selected_cats[0..(@selected_cats.length - 4)].length > 0 %>
      <strong>Viewing All Books with &nbsp</strong>
      <% @selected_cats[0..(@selected_cats.length - 4)].each do |cat| %>
        <%= cat %>
        <% if cat != @selected_cats[0..(@selected_cats.length - 4)].last %>
        , &nbsp
        <% end %>
      <% end %>
    <%= link_to "Back To All Books", books_path , class: "btn btn-outline-secondary mx-5" %>
    <% end %>
  </p>

  <div class="grid-container">
    <% @books.each do |book| %>
      <%= render "shared/card", width: "", book: book %>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <h1>Publish my book</h1>

  <%= render "shared/simple_form", book: @book %>
  
</div>

app/views/books/show.html.erb
<div class="container">

  <div class="d-flex justify-content-between">

    <% if @book.photo.present? %>
      <%= cl_image_tag @book.photo.key, class: "book-cover"%>
    <% else %>
      <img src="https://mpd-biblio-covers.imgix.net/9781250847959.jpg?" class="book-cover" alt="book-cover">
    <% end %>

    <div class="description" data-controller="select-amount">
      <div class="top-section">
        <div class="title">
          <h1><%= @book.title %></h1>
          <h5><i>By <%= @book.psuedoname %></i></h5>
        </div>

        <div class="value-list-item">
          <h4>Share price</h4>
          <p >€ <span data-select-amount-target="price"> <%= @book.current_share_value.round(2) %></span></p>
        </div>
      </div>

      <div class="d-flex justify-content-between">
        <div id="graph">
          <% if  @book.created_at == Date.today %>
            <img src="https://res.cloudinary.com/dsl9ixl0t/image/upload/v1670490792/starting-chart_ujqsfp.png" alt="chart" style="width:100%">
          <% elsif @book.current_share_value <= 1.6 %>
            <img src="https://res.cloudinary.com/dsl9ixl0t/image/upload/v1670490757/Losing-chart_ik5fty.png" alt="chart" style="width:100%">
          <% elsif @book.current_share_value > 1.6 %>
            <img src="https://res.cloudinary.com/dsl9ixl0t/image/upload/v1670490747/chart_1_ovhu6b.png" alt="chart" style="width:100%">
          <% end %>
        </div>

      <div class="item-right">
          <div id="share_value">
            <p>Total </p>
            <p>€ <span data-select-amount-target="text">0</span></p>
          </div>

        <div id="form" style="z-index: 100;">
          <%= simple_form_for [@book, @share] do |f| %>
          <%= f.input :share_amount, input_html: { value: 0,  "data-action": "change->select-amount#calculateValue", style: "z-index: 100;" }, label: "Select amount of shares" %>
          <input type="hidden" id="selected-value" name="selected-value" value="0" data-select-amount-target="value">
          <%= f.submit value: "SELL", class: "btn btn-outline-danger btn-lg", name: 'sell' %>
              <%= f.submit value: "BUY", class: "btn btn-outline-success  btn-lg", name: 'buy' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="tab-container">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true"><p>Description</p></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false"> <p>Author</p></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane" aria-selected="false"><p>Financials</p></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="disabled-tab" data-bs-toggle="tab" data-bs-target="#disabled-tab-pane" type="button" role="tab" aria-controls="disabled-tab-pane" aria-selected="false"><p>Analysis</p></button>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">

    <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
      <p><%= @book.description %></p>
    </div>

    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
      <p><%= @book.author_description %></p>
    </div>

    <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">
      <p>Financials</p>
    </div>

    <div class="tab-pane fade" id="disabled-tab-pane" role="tabpanel" aria-labelledby="disabled-tab" tabindex="0">
      <p>Analysis</p>
    </div>

  </div>

  <%= link_to "Edit", edit_book_path(@book) %>
  <%= link_to "Back", books_path %>

</div>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<div class="container">
  <%= link_to "#section-1", style: "text-decoration: none;" do %>
    <i class="fa-solid fa-hand-point-down fa-5x m-100 d-flex justify-content-center py-4"></i>
  <% end %>

  <section id="section-1">
  <div class="mission">
    <h2>Our Mission</h2>
      <p>The publishing industry has ignored underrepresented minorities for too long and Ghostwriter wants to put the power back in the author's pen. Ghostwriter wants to rewrite a world where authors aren't repressed by the publishing industry and are able to choose their own editors, illustrators and distributors. Where they aren't silenced by the limitations placed upon them by those who don't understand and don't support them. At Ghostwriter we beleieve that you know how to write for people like you.</p>

      <p>As the investment industry becomes more and more induvidualised, many communities are being left behind. We want to make investment more accessible for those who haven't been given the tools to learn, <strong>and</strong> we're making it fun <strong>and</strong>we're supporting a whole new generation of writers.</p>
  </div>

    <%= link_to "#section-2", style: "text-decoration: none;" do %>
      <i class="fa-solid fa-hand-point-down fa-5x m-100 d-flex justify-content-center my-5"></i>
    <% end %>
  </section>
  <section id="section-2">
    <div class="w-100 text-center my-3">
      <iframe width="840" height="457" src="https://www.youtube.com/embed/2AeOfYAJJ8o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="button-container">
      <%= link_to "I'm An Investor", learn_investment_path , class: "btn btn-outline-dark btn-lg"%>
      <%= link_to "I'm An Author", self_publication_path , class: "btn btn-outline-dark btn-lg" %>
    </div>
    <div class="m-100 text-center">
      <p>Or...</p>
      <%= link_to "Jump Straight To Library", self_publication_path , class: "btn btn-outline-secondary btn-lg" %>
    </div>
</div>
  </section>

app/views/pages/learn_investment.html.erb
<div class="container">
  <div class="title">
    <h1 class="title-li">Everything you need<br>to know about <br>investment</h1>
  </div>

  <%= link_to "#investment-section-1", style: "text-decoration: none;" do %>
    <i class="fa-solid fa-hand-point-down fa-5x m-100 d-flex justify-content-center py-5"></i>
  <% end %>

  <section id="investment-section-1">

    <div class="row gx-5">


      <div class="flip-card col-4">
        <div class="flip-card-inner">
          <div class="flip-card-front determine-risk" style="background-image: url('https://cdnblog.etmoney.com/wp-content/uploads/2021/06/5-Best-Senior-Citizen-Investment-Schemes-1200x499-1.png');">
            <h2>Determine Risk</h2>
          </div>
          <div class="flip-card-back">
            <p class="determine-risk">Why? Because there is more time available to recover any losses and less likelihood of being forced to sell out of the position too early. Bankroll: Determining the amount of money you can stand to lose is another important factor in figuring out your risk tolerance.</p>
          </div>
        </div>
      </div>

      <div class="flip-card col-4">
        <div class="flip-card-inner">
          <div class="flip-card-front buy-low" style="background-image: url('https://images.livemint.com/img/2022/03/02/1600x900/sip_1646241090555_1646241103965.jpg');">
            <h2>Buy Low Sell High</h2>
          </div>
          <div class="flip-card-back">
            <p class="buy-low">The benefits of Buy Low & Sell High are pretty obvious: You could generate very high returns, if successful. You're more likely to outperform the market then if you were investing in mutual funds. You could buy a lot of stock for a lower price.</p>
          </div>
        </div>
      </div>

      <div class="flip-card col-4">
        <div class="flip-card-inner">
          <div class="flip-card-front objection" style="background-image: url('https://pueblodeoro.com/wp-content/uploads/2021/07/Best-Property-Investment-Locations-in-the-Philippines.jpg');">
            <h2>Understand The Object Of Your Investment</h2>
          </div>
          <div class="flip-card-back">
            <p class="objection">Your objective should guide what types of assets you add to your portfolio. You might want to see the best possible tax results, minimize your risk as much as possible, or focus on a target-date goal, such as retirement. There are three types of investment objectives: growth, growth and income, or income.</p>
          </div>
        </div>
      </div>

      <div class="flip-card col-4">
        <div class="flip-card-inner">
          <div class="flip-card-front long-term" style="background-image: url('https://images.livemint.com/img/2021/07/05/600x338/835871664-k2sG--621x414@LiveMint_1625490426813.jpg');">
            <h2>Invest Long Term</h2>
          </div>
          <div class="flip-card-back">
            <p class="long-term">Short-term investments are held for less than a year, while long-term investments are held for a year or longer. Generally speaking, long-term investments are the best option for most individual investors, while short-term investments can be used if you are savvy enough to exploit openings.</p>
          </div>
        </div>
      </div>

      <div class="flip-card col-4">
        <div class="flip-card-inner">
          <div class="flip-card-front trends" style="background-image: url('https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/advisor/in/wp-content/uploads/2021/08/download-_11_-scaled-e1629366759454.jpg');">
            <h2>Don't Trust Trends</h2>
          </div>
          <div class="flip-card-back">
            <p class="trends">Herding behavior is behind most stock market bubbles. Two conditions for stock market bubbles are: new money inflows (which sustain the inflated price), and credit expansion (to generate the capital to invest). When credit conditions tighten, capital flows into the investment market slows and stocks start to decline.</p>
          </div>
        </div>
      </div>

      <div class="flip-card col-4">
        <div class="flip-card-inner">
          <div class="flip-card-front diversify" style="background-image: url('https://i0.wp.com/financebuddha.com/blog/wp-content/uploads/2018/01/16175526/Invest-to-get-return.jpg?fit=945%2C540&ssl=1');">
            <h2>Diversify Risk</h2>
          </div>
          <div class="flip-card-back">
            <p class="diversify">The most common sources of unsystematic risk are business risk and financial risk. Because it is diversifiable, investors can reduce their exposure through diversification. Thus, the aim is to invest in various assets so they will not all be affected the same way by market events.</p>
          </div>
        </div>
      </div>
    </div>

    <%= link_to "#investment-section-2", style: "text-decoration: none;" do %>
      <i class="fa-solid fa-hand-point-down fa-5x m-100 d-flex justify-content-center pb-5"></i>
    <% end %>
  </section>

<section id="investment-section-2">
  <div class="w-100 text-center py-5">
    <iframe class="youtube" width="560" height="315" src="https://www.youtube.com/embed/PHe0bXAIuk0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  <div class="text-center mt-5">
    <%= link_to "Get started", books_path , class: "btn btn-outline-dark btn-lg"%>
  </div>
</div>
</section>

app/views/pages/more_on_investment.html.erb
<div class="container"></div>

app/views/pages/user_balance.html.erb
<div class="container">
  <h1>Add credits to your account</h1>

      <%= form_with url: user_balance_path, method: :post do |form| %>
      <%= form.label :balance, "Fill in your deposit amount"%>

      <%= form.number_field :balance, in: 50..5000, step: 1 %>
      <%= form.submit "Pay", class: "style=button-grey;" %>
      <% end %>

      <%= form_with url: orders_path do %>
  <%= hidden_field_tag 'cash_wallet', @cash_wallet.id %>
  <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
<% end %>

</div>

app/views/pages/wallets.html.erb
<div class="container">
<h1>Add credits to your account</h1>

  <div class="payment-container row">

    <% @wallets.each do |wallet| %>
    <div class="payment-card col-4 px-0">
      <h4>Add €<%= wallet.cash_value %></h4>
        <%= form_with url: orders_path do %>
          <%= hidden_field_tag 'cash_wallet_id', wallet.id %>
          <%= submit_tag 'Purchase', class: 'button-grey' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-container">
    <h1>Ghostwriter</h1>
    <p>Rewriting the publishing industry to fit <strong>everyone</strong></p>
  </div>
</div>

app/views/shared/_dashboard.html.erb
<%= link_to book_shares_path(:book_id), style: "text-decoration: none;", class: "dashboard" do %>
  <div class="dashboard-container">
      <div class="portfolio-value">
        <div>
          <p>Wallet:</p>
        </div>

      </div>
      <div class="grid-dashboard">
        <div class="grid-dashboard-item">
          <p>Available Cash</p>
          <% if current_user.balance %>
            <p>€ <%= current_user.balance.round(2) %></p>
          <% else %>
            <p>0</p>
          <% end %>
        </div>
        <div class="grid-dashboard-item">
          <p>Earnings</p>
            <p>€12</p>
        </div>
        <div class="grid-dashboard-item">
          <p>Badges</p>
          <p><%= current_user.shares.count %> </p>
        </div>
      </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="home">
    <h2>Ghoswriter</h2>
  </div>
  <div class="learn-about">
    <%= link_to "View Library", books_path, class: "nav-link" %>
    <%= link_to "Our Mission", "/#section-1", class: "nav-link" %>
    <%= link_to "More On Self Publication", self_publication_path, class: "nav-link" %>
    <%= link_to "More On Investment", learn_investment_path, class: "nav-link" %>
  </div>
  <div class="dropdown">
    <%= image_tag "https://res.cloudinary.com/dipnvqfev/image/upload/v1677154163/remco-jonk-profile_zuyzp4.jpg", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
      <%= link_to "My portfolio",  book_shares_path(:book_id), class: "dropdown-item" %>
      <%= link_to "Publish my book", new_book_path, class: "dropdown-item"%>
      <%= link_to "Add credit",  wallets_path, class: "dropdown-item" %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    </div>
  </div>
</div>

app/views/shared/_simple_form.html.erb
<%= simple_form_for(book) do |f| %>
  <%= f.input :title, label: "What's the title of your book?", placeholder: "Your book title" %>
  <%= f.input :psuedoname, label: "Under what name would you like to publish?", placeholder: "Your Name" %>
  <%= "Please select three categories that best represent you or your book..."  %>
  <%= f.input :tag_list, legend_tag: false, html: {class: "d-flex"}, as: :check_boxes, collection: [ "Fantasy", "Romance", "Mystery", "Horror", "Thriller", "Paranormal", "Historical Fiction", "Sci-Fi", "Dystopian", "Memoir", "Art", "Self Help", "Motivational", "Health", "History", "Travel Guide", "Cookbook", "Poetry", "Erotic", "Female Author", "Trans Author", "Queer Author", "Non-Binary Author", "POC Author", "Black Author", "Asian Author", "LatinX Author", "Indegenous Author", "Agender Author", "Polysexual Author", "Disabled Author", "Neurodivergent Author", "Literary Prize", "Critically Acclaimed", "Dark", "Cerebral", "Inspiring", "Slow-Burn", "Psychological", "Quirky", "Coming Of Age", "Cultural", "Social Commentary", "Sunday Reading", "Guilty Pleasure", "Strong Female Lead", "Queer Romance" ] %>
  <%= f.input :description, label: "Please take some time to describe your book", placeholder: "Max 500 characters" %>
  <%= f.input :author_description, label: "Can you tell us a little bit about yourself?", placeholder: "Max 500 characters" %>
  <%= f.input :example, label: "Here you can paste in an extract of your book for potential investors to read...", placeholder: "Max 1000 characters" %>
  <%= f.input :photo, label: "Please upload your cover art...", as: :file %>
  <%= link_to self_publication_path, class: "custom-label cursor-pointer", target: "blank" do %>
  <%= "What are the costs of publishing your book? <strong>click here for information on the costs of self publication</strong>".html_safe %>
  <% end %>
  <%= f.input :initial_share_value, :input_html => { value: 1, step: 0.05 }, placeholder: "€", label: false %>

  <%= link_to learn_investment_path, class: "custom-label cursor-pointer", target: "blank" do %>
    <%= "How many shares do you want to sell? <strong>click here for information share values</strong>".html_safe %>
  <% end %>
  <%= f.input :total_amount, :input_html => { value:  10000, step: 100 }, label: "How many shares", label: false %>
  <%= f.submit value: "Publish", class: "btn btn-outline-dark btn-large" %>
<% end %>